POST http://localhost:5119/statement
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="payload.Statement"; filename="fundingbank_3.pdf"
Content-Type: application/pdf

< ./data/fundingbank_3.pdf
--boundary--